[package]
name = "kubectl-config-doctor"
version = "0.1.0"
edition = "2021"

[dependencies]
colorize = "0.1.0"
home = "0.5.9"
k8s-openapi = { version = "0.22.0", features = ["latest"] }
kube = { version = "0.94.1", features = ["config", "client"] }
tokio = { version = "1.40.0", features = ["full"] }

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1